### ISSUE TITLE
--resolve not working?

### ISSUE THREAD

**Issue by Johj** [ownaginatious/fbchat-archive-parser#37]
--resolve seems to get stuck after entering your email. The password prompt ("Facebook password:") does not display at all and I'm forced to end the process.

What I'm trying to do is "fbcap ./messages.htm -f json --resolve > messages.json" and I'm on version 0.9.post3.

**Comment by ownaginatious** [comment]
I'm not able to reproduce your issue. What operating system and Python version are you using?

**Comment by Johj** [comment]
Windows 10 and Python 3.5.2.

**Comment by ownaginatious** [comment]
I believe I've fixed the issue under Windows. Please try version `0.9.post4`. Thanks!

**Comment by Johj** [comment]
Thanks for the quick patch, appreciate the effort.

The password prompt now appears but the next issue that's cropped up is that it seems to freeze after entering my credentials. I thought maybe it had to do with my 2FA or Code Generator being enabled but no cigar even after disabling those security features.

**Comment by ownaginatious** [comment]
Does this happen even when not redirecting to a file?

**Comment by Johj** [comment]
Yeah, it still freezes after entering credentials with or without redirecting to file.

I added some print statements in main.py:
```
    sys.stderr.write("Facebook password: ")
    print('a')
    sys.stderr.flush()
    print('b')
    password = getpass.getpass("")
    print('c')
    name_resolver = FacebookNameResolver(email, password)
    print('d')
```
and `getpass.getpass("")` never seems to return (c and d are not printed).

**Comment by ownaginatious** [comment]
Hmm, `getpass.getpass("")` should basically just capture input from the keyboard, but not display it in the terminal while you type it. The argument `""` is the prompt text to the user. Windows apparently has a dumb issue where it won't print this prompt to `stderr` and instead to `stdout`, which ends up going into your file instead. That was the issue you were experiencing when you opened this ticket.

I fixed that issue by manually writing the prompt to `stderr` and making the `getpass` prompt empty.

When you get to that line, you're supposed to copy-paste/type your password and hit enter in the terminal. Is it still freezing even after doing that?

**Comment by Johj** [comment]
Yeah, my cursor just blinks on the next line after entering password.

**Comment by Johj** [comment]
Kind of hacky but I switched to just using input() for password and it worked fine.
```py
  import platform
  
  if platform.system() == "Windows":
    password = six.moves.input()
  else:
    password = getpass.getpass("")
```
Also had to disable my 2FA (the warning notification that popped up when 2FA was enabled):
![chrome_2017-04-11_15-27-30](https://cloud.githubusercontent.com/assets/16639331/24933565/caf71a32-1ecb-11e7-8a9d-3a6ec644aa0f.png)

**Comment by ownaginatious** [comment]
Ah, thanks for trying that out :+1: I'll look further into it later to see if I can get `getpass(...)` to work properly.

Yeah, unfortunately there isn't an easy way around that. I listed the `--resolve` thing is a beta feature since it essentially just grabs a chunk of JSON floating around your Facebook friends page to map the IDs to names.

The "proper" way of doing this would be to create a Facebook app and authorize it to access your friends list. That's a lot more work and much more annoying for the end user. I was hoping the hacky `--resolve` feature would be a good enough holdover until Facebook finally fixes the issue on their end... if ever :(

**Comment by Johj** [comment]
No problem and all in all thanks for the quick responses. I'll be sure to give this program another go if/when you find the workaround. Great tool!

**Comment by ownaginatious** [comment]
Super old now, but I think I was able to resolve this issue recently by doing the password prompting via a third-party library instead.

Not sure if the `--resolve` option is even necessary anymore, given that Facebook has randomly started supplying full names with each message again (at least for me). Anyway, if you want, you could try it out again with the latest on PyPI: `1.0`

**Comment by Johj** [comment]
Yep, I just downloaded an updated version of my Facebook data and the full names were there for me as well.

I didn't try using the `--resolve` option (so I wasn't able to try your updated password prompting) but it seems to be a non-issue now that Facebook's data isn't janky in the first place. Feel free to close this issue at your leisure.
